# Travis CI будет использовать язык java.
language: java
install: true

# Версия JDK для сборки проекта
jdk: oraclejdk11

os:
  - linux

dist: xenial

# После выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# И отправлять на сервис https://codecov.io/
after_success: bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN="30ff4423-ab12-41c1-82d4-adc0d9f9136d"
